version: "3.4"

services:
    api:
        build:
          context: Back-End/EServices.WebApi/ 
          dockerfile: Dockerfile
        ports:
          - "9000:80"
        depends_on:
          - db
        restart: always

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "Mm@12345"
            ACCEPT_EULA: "Y"
        volumes:
          - sql_server_data:/var/opt/mssql
        restart: always

    ui:
        build:
          context: Front-End/angular/ 
          dockerfile: Dockerfile
        ports:
          - "80:80"
        links:
         - api
        restart: always

volumes:
  sql_server_data:
    driver: local
